#include<iostream>
#include<stdlib.h>
#include<ctime>
using namespace std;
int main(){

    string name,end;
    int choice=0,round,start=1,number;
    int computer=0,player=0;

    //  Your Name
    cout<<"\n\n --*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--\n\n";
    cout<<"                            NAME   \n\n";
    cout<<" --*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--\n\n";

    cout<<"Enter the name : ";
    getline(cin,name);

    cout<<"\n --*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--\n\n";
    cout<<"                      ROUNDS\n\n";
    cout<<"  --*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--\n\n";

    cout<<name<<" How Many Rounds You Want To Play ?: ";
    cin>>round;

    do{
        
    //RANDOM VALUE GENERATED BY COMPUTER 
    srand(time(0));
    number = rand() % 3 + 1;

    cout<<" --*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--\n\n";
    cout<<"                             GAME\n"<<endl;
    cout<<"   --*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--\n\n";

    // SCORE SECTION

    cout<<" Round No  : "<<start<<"/"<<round <<endl<<endl;
    cout<<" 1) ROCK \n\n 2) PAPER \n\n 3) SCISSOR \n"<<endl;

    //player choice 
    cout<<" Select Your Choice : ";
    cin>>choice;
    cout<<"\n"<<endl;

    // computer choice 
    cout<<" Computer Choice is : "<<number<<"\n"<<endl;
    cout<<""<<endl;

    // ROCK IS STRONGER THAN SCISSOR BUT WEAKER THAN PAPER , PAPER IS STRONGER THAN ROCK BUT WEAKER THAN SCISSOR AND SCISSOR IS STRONGER THAN PAPER AND WEAKER THAN ROCK.
    if(choice == number){
        cout<<" \n DRAW\n\n"<<endl;
    }
    
    if (choice == 1 && number == 3){
        if(choice < number){
             cout<<" \n " <<name <<" win\n\n"<<endl;
            player++;
        }
    }

    else if(choice == 1 && number == 2){
        if(choice < number){
             cout<<" \n computer win\n\n"<<endl;
            computer++;
        }
    }

    else if(choice == 2 && number == 3){
        if(number > choice){
             cout<<" \n computer win\n\n"<<endl;
            computer++;
        }
    }
    
    else if(choice == 2 && number == 1){
        if(choice > number){
             cout<<" \n " <<name <<" win\n\n"<<endl;
            player++;
            
        }
    }
    else if(choice == 3 && number == 1){
        if(choice > number){
             cout<<" \n computer win\n\n"<<endl;
            computer++;
        }
    }
    else if(choice == 3 && number == 2){
        if(number < choice){
            cout<<" \n " <<name <<" win\n\n"<<endl;
            player++;

        }
    }
    // PRESSING ANY KEY FEATURE 
    cout<<" Press Y To Continue... ";
    cin>>end;

    cout<<"\n";

    start++;

    }while(round >= start);

    cout<<"\n";

    // FINAL SCORE
    cout<<"              ---- Final Score  ----   \n"<<endl;

    cout<<" "<<name<<"'s "<<" Score = "<<player <<endl<<endl;
    cout<<" Computer Score = "<<computer<<endl<<endl;

    // WHO WIN THE GAME ?
    if(player > computer){
        cout<<name<<" you won the game "<<endl;
    }

    else if(player < computer){
        cout<<name<<" you lose the game "<<endl;
    }

    else if( player == computer){
        cout<<" Match Draw ... ";
    }

    return 0;
}

